### ISSUE TITLE
Add ITPK

### ISSUE THREAD

**Issue by kylehutson** [FlintHillsIO/manhattech#1]
Need to add a local group "Information Technology Professionals of Kansas (ITPK)". This is an association of those that work as IT professionals in the Manhattan area. https://www.facebook.com/groups/itpks/

**Comment by brycejohnston** [comment]
@kylehutson thanks, I will get this added to the groups page!

**Comment by brycejohnston** [comment]
@kylehutson got it added, please let ITPK know about the website when you have a chance, thanks
